replicaCount: 1

image:
  repository: ez3kiel/uptimerobot-exporter:latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

healthPath: /health

podMonitor:
  enabled: true
  path: /metrics
  interval: 1m
  scrapeTimeout: 1m

uptimerobot:
  apiKey: replace-me-plz

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
